version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80

  app:
    build: 
      context: .
      dockerfile: ./src/Dockerfile
      args:    
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
