version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./containers/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - app
    tty: true
  
  app:
    build: 
      context: ./src
      dockerfile: Dockerfile
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    image: rails:dev
    volumes:
      - ./src:/hangartalk
      - ./src/vendor/bundle:/hangartalk/vendor/bundle
    environment:
      TZ: 'Asia/Tokyo'
      RAILS_ENV: development
      # API_DOMAIN: "localhost:$FRONT_PORT"
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true

  db:
    image: mysql:8.0.28
    volumes:
      - ./etc/my.cnf:/etc/mysql/conf.d/my.cnf
      - hangartalk_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    env_file:
      - .env
    tty: true

volumes: 
  hangartalk_data:
    external: true