version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    environment:
      TZ: Asia/Tokyo
    ports:
      - 80:80

  app:
    build: 
      context: .
      dockerfile: ./api/Dockerfile
      args:    
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    environment:
      TZ: Asia/Tokyo