default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV.fetch("MYSQL_DATABASE_HOST") { 'db' } %>  # Docker用
  # host: localhost  # Local用
  socket: /tmp/mysql.sock
development:
  <<: *default
  database: hangartalk_development
test:
  <<: *default
  database: hangartalk_test
production:
  <<: *default
  database: hangartalk_production
  <% if Rails.application.credentials.db.present? %>
    username: <%= Rails.application.credentials.db[:user_name] %>
    password: <%= Rails.application.credentials.db[:password] %>
    host: <%= Rails.application.credentials.db[:endpoint] %>
  <% end %>
  port: 3306