default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: hanger-talk_development
  socket: /tmp/mysql.sock
test:
  <<: *default
  database: hanger-talk_test
  socket: /tmp/mysql.sock
production:
  <<: *default
  database: hanger-talk_production
  socket: /var/run/mysqld/mysqld.sock
