default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: hangertalk_development
  socket: /tmp/mysql.sock
test:
  <<: *default
  database: hangertalk_test
  socket: /tmp/mysql.sock
production:
  <<: *default
  database: hangertalk_production
  socket: /var/run/mysqld/mysqld.sock
