default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  socket: /tmp/mysql.sock 

development:
  <<: *default
  database: hanger_talk_prototype_development

test:
  <<: *default
  database: hanger_talk_prototype_test

production:
  <<: *default
  database: hangertalk_production
  