source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.1'
gem 'rails', '~> 6.1.4', '>= 6.1.4.4'
gem 'bcrypt',  '3.1.16'
gem 'mysql2', '~> 0.5'
gem "dotenv-rails"    # MySQL用の環境変数管理gem
gem 'puma', '~> 5.0'
gem 'webpacker', '~> 5.0'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.7'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'faker'
gem 'active_storage_validations'
gem 'image_processing'
gem 'mini_magick'
gem 'aws-sdk-s3', require: false
gem 'parser', '>= 3.0.0.0'
gem 'kaminari'
gem 'rails-i18n', '~> 6.0'
gem 'devise'
gem 'devise-i18n'
gem "tailwindcss-rails", "~> 2.0"

gem 'pry-rails'
gem 'pry-byebug'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~> 5.0.0'
  gem 'factory_bot_rails'
  gem 'capybara', '>= 3.26'  # Adds support for Capybara system testing and selenium driver
  gem 'selenium-webdriver'
  gem 'webdrivers'  # Easy installation and use of web drivers to run system tests with browsers
end

group :development do
  gem 'web-console', '>= 4.1.0'   # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'rack-mini-profiler', '~> 2.0'
  gem 'listen', '~> 3.3'
  gem 'spring'
  gem 'solargraph'  # improve IntelliSense of VSCode
  gem 'pre-commit'
  gem 'rubocop'
  gem 'rubocop-rails'
end
