name: CD
on:
  push: # 指定したブランチにpushされた際に実行
    # branches: [ feature/aws-ci-cd ]
  # workflow_run:
  #   workflows: ["CI"]
  #   branches: [main]
  #   types: [completed]
jobs:
  ecs_deploy:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: aws authentication
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name : ecr login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: build and push
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker-compose -f docker-compose.production.yml build
          docker image tag hangartalk_app $ECR_REGISTRY/app:latest
          docker image tag hangartalk_nginx $ECR_REGISTRY/nginx:latest
          docker push $ECR_REGISTRY/app:latest
          docker push $ECR_REGISTRY/nginx:latest
      - name: sleep
        run: sleep 10
      - name: update service
        run: |
          aws ecs update-service --cluster hangartalk --service hangartalk --force-new-deployment