name: CI
on:
  push:
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    services:
      mysql:
        image: mysql:8.0.28
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          BIND-ADDRESS: 0.0.0.0
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      RAILS_ENV: test
      DB_HOST: 127.0.0.1
    steps:
      - uses: actions/checkout@v2.3.4
      - name: set up ruby
        uses: ruby/setup-ruby@v1.68.0
        with:
          ruby-version: 3.0.1
          bundler-cache: true
      - name: cache node modules
        uses: actions/cache@v2.1.4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-
      - name: bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --path vendor/bundle
      - name: yarn install
        run:  yarn install --check-files
      - name: migrate db
        run: |
          bundle exec rails db:create
          bundle exec rails db:test:prepare
      - name: run rspec
        run: bundle exec rspec
